apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cobblepod-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ui.ingress.issuer }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.ui.ingress.host }}
    secretName: cobblepod-tls
  rules:
  - host: {{ .Values.ui.ingress.host }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: cobblepod-server
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cobblepod-ui
            port:
              number: 80
