name: Test Docker Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'Dockerfile'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/backend-docker-build.yml'
      - '.github/workflows/docker-build-reusable.yml'

jobs:
  test-build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      context: '.'
      platforms: 'linux/amd64'
      push: false
      image-name: 'cobblepod-backend-test'
      tags-input: 'cobblepod-backend-test:test'
      use-metadata: false
      login-required: false