name: Test UI Docker Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/ui-docker-build.yml'
      - '.github/workflows/docker-build-reusable.yml'

jobs:
  test-build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-build-reusable.yml
    with:
      context: './ui'
      platforms: 'linux/amd64'
      push: false
      image-name: 'cobblepod-ui-test'
      tags-input: 'cobblepod-ui-test:test'
      use-metadata: false
      login-required: false
